name: Test WorkFlow

on: 
  release:
    types: [published]   
  push:
    branches: 
      - master     
  schedule:
    - cron: 0 */48 * * *  
  watch:
    types: started

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Clone Source Codes & Alter Feeds
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master 
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        pwd
        ls -al
        cd openwrt
        pwd
        ls -al
        echo "src-git ssrp https://github.com/fw876/helloworld.git" >> ./feeds.conf.default
        echo "src-git kenzo https://github.com/kenzok8/openwrt-packages.git" >> ./feeds.conf.default
        echo "src-git small https://github.com/kenzok8/small.git" >> ./feeds.conf.default
        cd package
        git clone https://github.com/kenzok8/openwrt-packages.git
        pwd
        ls -al

    - name: Import / Generate Config File
      run: |
        pwd
        ls -al
        git clone https://github.com/Neurotoxin0/External_Config_File.git
        mv ./External_Config_File/.config ./
        ls -al
        make defconfig
      # run: make menuconfig

    - name: Personalized
      run: |
        sed -i 's/192.168.1.1/192.168.31.2/g' ./package/base-files/files/bin/config_generate
        
    - name: Download Make File
      run: |
        make download -j8
        find dl -size -1024c -exec rm -f {} \;