name: TEST

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ./Source_Code/
        
    - name: List Dirs
      run: |
        echo "Current Dir:"
        pwd
        echo "-------------------------------------------------"
        du -h --max-depth=1 ./
        echo "-------------------------------------------------"
    
    
